/* Generated By:JavaCC: Do not edit this line. PDDL21parserConstants.java */
package javaff.parser;

public interface PDDL21parserConstants {

  int EOF = 0;
  int OPEN = 5;
  int CLOSE = 6;
  int DEFINE = 7;
  int DOMAIN = 8;
  int DOMAIN_LABEL = 9;
  int OBJECTS = 10;
  int GOAL = 11;
  int INIT = 12;
  int METRIC = 13;
  int PROBLEM = 14;
  int REQUIREMENTS = 15;
  int REQUIREMENT_LABELS = 16;
  int NON_HANDLED_LABELS = 17;
  int TYPES = 18;
  int EITHER = 19;
  int CONSTANTS = 20;
  int PREDICATES = 21;
  int FUNCTIONS = 22;
  int ACTION = 23;
  int DURATIVE_ACTION = 24;
  int PARAMETERS = 25;
  int DURATION = 26;
  int DUR_VAR = 27;
  int PRECONDITION = 28;
  int CONDITION = 29;
  int EFFECT = 30;
  int AND = 31;
  int NOT = 32;
  int OVER_ALL = 33;
  int AT_START = 34;
  int AT_END = 35;
  int EQUALS = 36;
  int TYPE_IDENT = 37;
  int BINARY_OP = 38;
  int BINARY_COMP = 39;
  int ASSIGN_OP = 40;
  int ASSIGN = 41;
  int SCALE_UP = 42;
  int SCALE_DOWN = 43;
  int INCREASE = 44;
  int DECREASE = 45;
  int OPTIMIZATION = 46;
  int MINIMIZE = 47;
  int MAXIMIZE = 48;
  int TOTAL_TIME = 49;
  int VAR = 50;
  int NUMBER = 51;
  int NAME = 52;
  int SINGLE_LINE_COMMENT = 53;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"define\"",
    "\"domain\"",
    "\":domain\"",
    "\":objects\"",
    "\":goal\"",
    "\":init\"",
    "\":metric\"",
    "\"problem\"",
    "\":requirements\"",
    "<REQUIREMENT_LABELS>",
    "<NON_HANDLED_LABELS>",
    "\":types\"",
    "\"either\"",
    "\":constants\"",
    "\":predicates\"",
    "\":functions\"",
    "\":action\"",
    "\":durative-action\"",
    "\":parameters\"",
    "\":duration\"",
    "\"?duration\"",
    "\":precondition\"",
    "\":condition\"",
    "\":effect\"",
    "\"and\"",
    "\"not\"",
    "\"over all\"",
    "\"at start\"",
    "\"at end\"",
    "\"=\"",
    "\"-\"",
    "<BINARY_OP>",
    "<BINARY_COMP>",
    "<ASSIGN_OP>",
    "\"assign\"",
    "\"scale-up\"",
    "\"scale-down\"",
    "\"increase\"",
    "\"decrease\"",
    "<OPTIMIZATION>",
    "\"minimize\"",
    "\"maximize\"",
    "\"total-time\"",
    "<VAR>",
    "<NUMBER>",
    "<NAME>",
    "<SINGLE_LINE_COMMENT>",
  };

}
