server:
  port: 9000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: articles
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

destinations:
  queues:
    NYSE:
      exchange: nyse
      routing-key: NYSE
      durable-queue: true
    IBOV:
      exchange: ibov
      routing-key: IBOV
      durable-queue: true

  topics:
    distance:
      exchange: alerts
      routing-key: DISTANCE
      durable-queue: false
    commands:
      exchange: alerts
      routing-key: COMMANDS
      durable-queue: true
